name: 💡 Match-Hub-UI Push - Light CI

on:
  push:
    branches:
      - "**" # Match all branches
      - "!main" # Exclude the main branch (which runs the CD pipeline)
    paths:
      - "apps/match-hub-ui/**"
      - "package.json"
      - "package-lock.json"

# CONCURRENCY: Ensures only the latest commit on a branch is processed, cancelling older runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-build:
    name: Verify Build Success (Match-Hub-UI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # CACHING: Caches node_modules based on the lock file content for speed.
      - name: Setup Node and Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # REMOVED: cache: 'npm' was causing the root package.json ENOENT error
          cache-dependency-path: "apps/match-hub-ui/package-lock.json"

      - name: Install Dependencies
        # Using 'npm install' to bypass strict lock file checks
        run: npm install --no-fund
        working-directory: apps/match-hub-ui

      - name: 🧪 Run All Tests (Unit & E2E)
        # This new command chains the unit tests (headless) and the E2E tests (which includes build/serve)
        run: npm run test:full
        working-directory: apps/match-hub-ui
      # --- ARTIFACT UPLOAD STEP (MAKES REPORT VIEWABLE) ---
      - name: ⬆️ Upload Coverage Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          # This path is relative to the 'working-directory' (apps/match-hub-ui).
          # It uses the confirmed default output path from the Angular CLI.
          path: coverage/match-hub-ui
          retention-days: 7
          # Allow the step to warn (instead of fail) if the coverage files weren't produced
          if-no-files-found: warn


      - name: Simple Build Success Message
        run: echo "✅ Match-Hub-UI build check passed quickly."
